### ISSUE TITLE
FEATURE-REQUEST: PNPM support

### ISSUE THREAD

**Issue by mheob** [go-task/go-npm#2]
It would be nice to use this nice tool also with PNPM as package manager.

**Comment by andreynering** [comment]
Hi @mheob,

I'm not familiar with pnpm. What is needed to support it?

**Comment by mheob** [comment]
Hi @andreynering.

Sorry, I missed your reply.

PNPM uses a non-flat and symlinked `node_modules` structure which offers [many advantages](https://blog.bitsrc.io/stop-using-npm-yarn-use-pnpm-instead-baa640698be6). More and more projects and companies are switching to pnpm. E.g. [vercel with next.js and other projects](https://github.com/vercel/next.js/), just to name one of the big ones.

The details are a bit complex to explain for me. Therefore I would like to refer to the [official documentation](https://pnpm.io/motivation).

The error I am getting by using `go-npm` with `pnpm` looks like:

```console
$ pnpm install

Lockfile is up to date, resolution step is skipped
Already up to date

 > use-correct-pm@1.0.4 postinstall /Users/mheob/dev/tools/use-correct-pm
 > is-ci || go-npm install

Downloading from URL: https://github.com/mheob/use-correct-pm/releases/download/v1.0.4/use-correct-pm_1.0.4_darwin_amd64.tar.gz
Error: Error finding binary installation directory
    at /Users/mheob/dev/tools/use-correct-pm/node_modules/.pnpm/@go-task+go-npm@0.1.16/node_modules/@go-task/go-npm/bin/index.js:2:909476
    at ChildProcess.exithandler (node:child_process:420:5)
    at ChildProcess.emit (node:events:513:28)
    at maybeClose (node:internal/child_process:1091:16)
    at Socket.<anonymous> (node:internal/child_process:449:11)
    at Socket.emit (node:events:513:28)
    at Pipe.<anonymous> (node:net:313:12)
 ELIFECYCLE  Command failed with exit code 1.
```

So it appears to me that the `bin` directory cannot be found, although it is there (it can be checked via [`pnpm bin`](https://pnpm.io/cli/bin)).

```console
$ pnpm bin
/Users/mheob/dev/tools/use-correct-pm/node_modules/.bin
```

I hope this explanation helps a bit.

**Comment by andreynering** [comment]
Thanks for the explanation.

If anyone wants to give this a try, we probably need to check for the right ENVs for pnpm here:

https://github.com/go-task/go-npm/blob/0827f8924458a235cf03e01fe2b22198929b98e5/src/common.js#L36-L42

**Comment by mheob** [comment]
Yes, I will try it in a couple of days.
I already have an idea how it could work.
