### ISSUE TITLE
BUG: On Windows, binaries are installed in the wrong location

### ISSUE THREAD

**Issue by sounisi5011** [go-task/go-npm#4]
On Windows, the globally installed CLI is placed in the `{npm_config_prefix}` directory, not the `{npm_config_prefix}/bin` directory.

> When in global mode, executables are linked into `{prefix}/bin` on Unix, or <mark>directly into `{prefix}` on Windows</mark>. Ensure that path is in your terminal's `PATH` environment to run them.
> --- [folders | npm Docs](https://docs.npmjs.com/cli/v9/configuring-npm/folders#executables)

However, the current installation logic seems to always install in the `bin` directory:

https://github.com/go-task/go-npm/blob/5b4b644df7ad8e5564885a514f57fe3d3999ad9b/src/common.js#L41-L43

I think this code needs to be fixed like this:

```diff
       if (env && env.npm_config_prefix) {
-        dir = join(env.npm_config_prefix, 'bin');
+        if (process.platform === 'win32') {
+          dir = env.npm_config_prefix;
+        } else {
+          dir = join(env.npm_config_prefix, 'bin');
+        }
       } else if (env && env.npm_config_local_prefix) {
```

**Comment by sounisi5011** [comment]
If this is granted, I would like to create a pull request to reflect this fix.

**Comment by andreynering** [comment]
Hi @sounisi5011,

Yes, a PR would be helpful!
